# Generated by Django 4.2.29 on 2026-04-30 19:03

import bbf.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBFClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_reference', models.CharField(default=bbf.models.generate_claim_reference, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_subcounty', 'Awaiting Subcounty'), ('awaiting_county', 'Awaiting County'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcounty_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('county_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('county_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_confirmed_claims', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbf_claims', to=settings.AUTH_USER_MODEL)),
                ('subcounty_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcounty_confirmed_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BBFBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.CharField(choices=[('child', 'Child'), ('spouse', 'Spouse'), ('parent_mother', 'Mother'), ('parent_father', 'Father')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='bbf_documents/')),
                ('document_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_beneficiaries', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='bbf.bbfclaim')),
            ],
        ),
    ]
