# Generated by Django 5.0.1 on 2026-05-06 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBFClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('payslip', 'Member Payslip'), ('national_id', 'Member National ID'), ('burial_permit', 'Deceased Burial Permit'), ('deceased_id', 'Deceased ID or Birth Certificate or Birth Notification'), ('relationship', 'Proof of Relationship'), ('introduction', 'Introduction Letter from Head of Institution')], max_length=20)),
                ('file', models.FileField(upload_to='bbf_claim_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_documents', to='bbf.bbfclaim')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claim_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('claim', 'document_type')},
            },
        ),
    ]
