# Generated by Codex on 2026-04-25

from django.db import migrations


PNG_TO_JPG_MAP = {
    "gallery_covers/cover1.png": "gallery_covers/cover1.jpg",
    "gallery_covers/cover2.png": "gallery_covers/cover2.jpg",
    "gallery_covers/cover3.png": "gallery_covers/cover3.jpg",
}


def update_cover_extensions(apps, schema_editor):
    GalleryAlbum = apps.get_model("core", "GalleryAlbum")

    for old_path, new_path in PNG_TO_JPG_MAP.items():
        GalleryAlbum.objects.filter(cover_image=old_path).update(cover_image=new_path)


def revert_cover_extensions(apps, schema_editor):
    GalleryAlbum = apps.get_model("core", "GalleryAlbum")

    for old_path, new_path in PNG_TO_JPG_MAP.items():
        GalleryAlbum.objects.filter(cover_image=new_path).update(cover_image=old_path)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_becmember_bgcmember"),
    ]

    operations = [
        migrations.RunPython(update_cover_extensions, revert_cover_extensions),
    ]
