# Generated by Django 4.2.29 on 2026-04-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_gallery_cover_extensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'ordering': ['slider_order', 'title']},
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='show_on_homepage_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='slider_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
