# Generated by Django 4.2.29 on 2026-05-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_galleryalbum_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='slider_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
