# Generated by Django 4.2.29 on 2026-04-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BBFContribution',
        ),
    ]
