# Generated by Django 4.2.29 on 2026-04-23 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_bbfcontribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsc_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BBFContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_date', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbf_contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
