# Generated by Django 4.2.29 on 2026-04-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_legacyteacher_bbfcontribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
